name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker TEST image
        run: docker build -t jdh96romeo/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
        run: docker run -e CI=true jdh96romeo/react-test npm run test

      - name: Build Docker PROD image / multi-client
        run: docker build -t jdh96romeo/multi-client ./client
      
      - name: Build Docker PROD image / multi-nginx
        run: docker build -t jdh96romeo/multi-nginx ./nginx
      
      - name: Build Docker PROD image / multi-server
        run: docker build -t jdh96romeo/multi-server ./server
      
      - name: Build Docker PROD image / multi-worker
        run: docker build -t jdh96romeo/multi-worker ./worker

      - name: Push Docker PROD images to Docker Hub / multi-client
        run: docker push jdh96romeo/multi-client
      
      - name: Push Docker PROD images to Docker Hub / multi-nginx
        run: docker push jdh96romeo/multi-nginx
      
      - name: Push Docker PROD images to Docker Hub / multi-server
        run: docker push jdh96romeo/multi-server
      
      - name: Push Docker PROD images to Docker Hub / multi-worker
        run: docker push jdh96romeo/multi-worker