name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker test image
      - run: docker build -t jdh96romeo/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run tests
      - run: docker run -e CI=true jdh96romeo/react-test npm test

      - name: Build Docker prod images
      - run: docker build -t jdh96romeo/multi-client ./client
      - run: docker build -t jdh96romeo/multi-nginx ./nginx
      - run: docker build -t jdh96romeo/multi-server ./server
      - run: docker build -t jdh96romeo/multi-worker ./worker

      - name: Push Docker prod images to Docker Hub
      - run: docker push jdh96romeo/multi-client
      - run: docker push jdh96romeo/multi-nginx
      - run: docker push jdh96romeo/multi-server
      - run: docker push jdh96romeo/multi-worker